services:
  blinko:
    image: blinkospace/blinko:1.8.7
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://${APP_DOMAIN}
      - NEXT_PUBLIC_BASE_URL=https://${APP_DOMAIN}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=postgresql://postgres:${BLINKO_POSTGRES_PASSWORD}@postgres:5432/postgres
    volumes:
      - ${APP_DATA_DIR}/data/blinko:/app/.blinko
    healthcheck:
      test: wget --spider -q http://127.0.0.1:1111/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    x-runtipi:
      is_main: true
      internal_port: 1111

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${BLINKO_POSTGRES_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d postgres || exit 1
      interval: 5s
      timeout: 10s
      retries: 5

x-runtipi:
  schema_version: 2
